name: Happy Valley Node School

pygment: true
markdown: kramdown

timezone: America/New_York
encoding: utf-8

exclude: ['Dockerfile', 'Gemfile', 'README.md', 'Vagrantfile', 'provision.sh']

relative_permalinks: true

permalink:     pretty
paginate_path: 'page:num'
paginate: 10

collections:
 - event

inc:
  # Blog Information
  title:        "Happy Valley Node School"
  subtitle:     "A P2P node.js learning workshop in State College, PA., using the nodeschool.io open source choose-your-own-adventure lessons."
  cover_image:  blog-cover.jpg
  logo:         logo.png

  # Company information
  company:      Incorporated
  url:          http://sendtoinc.com/
  facebook:     sendtoinc
  twitter:      sendtoinc
  gplus:        '101183822199340201470'
  about_link:   https://sendtoinc.com/about/

  # Product Information
  product_link: http://nodeschool.io/
  tagline:      "Learn node at your own pace"

  # Comments
  disqus:
    # Eg. "exampleblog" Set to false to disable comments
    shortname:  false

  # Sharing settings
  sharing:
    twitter:    false
    facebook:   false
    gplus:      false
    hn:         false

 # Analytics     
  analytics:
    google: false # Add tracking code in _includes/_google-analytics.html

  # Google Fonts
  # eg. 'Droid+Sans:400,700|Droid+Serif:400,700'
  google_font: 'Droid+Sans:400,700'